### ISSUE TITLE
@mentions don't seem to be working

### ISSUE THREAD

**Issue by Ocelot08** [cameroncros/OctoPrint-DiscordRemote#181]
Bot seems to write out "@ocelot08" but it does not work as a mention.

Also tried @ocelot09#XXXX and <@#[User ID Number]#> neither worked. 

I'm new to this so am I missing something?

**Comment by cameroncros** [comment]
As per https://github.com/cameroncros/OctoPrint-DiscordRemote/issues/83,
mentions are broken inside embeds.

**Comment by NarodGaming** [comment]
> As per #83, mentions are broken inside embeds.

What happened to the changes made on: https://github.com/cameroncros/OctoPrint-DiscordRemote/pull/130 (PR#130)?

I can't seem to find any reference to how to set this up, has this been removed since?

**Comment by cameroncros** [comment]
I think it was removed, as it was broken. It didnt fix the mentions problem
though.

**Comment by Prototype7813** [comment]
Hi ! Is it possible to find a fix to it ? I choose discord like main notification center and the mentions is the only thing that can notify me for real important stuff like the end of a print or some failure state. Would be really great since i have everything that i want with your plugin except that!

**Comment by cameroncros** [comment]
I am working on using discord.py, which may help, but I can't promise
anything at this stage.
